import Database from 'better-sqlite3';import os from 'node:os';import path from 'node:path';import fs from 'node:fs';import type {Quality,QuestionFormat,KnowledgeType,ScoreCard} from '../shared/types.js';
const dataDir=path.join(os.homedir(),'.fitword');fs.mkdirSync(path.join(dataDir,'sessions'),{recursive:true});
export const db=new Database(process.env.FITWORD_DB??path.join(dataDir,'fitword.db'));
db.pragma('journal_mode = WAL');
db.exec(`CREATE TABLE IF NOT EXISTS questions(id INTEGER PRIMARY KEY,format TEXT NOT NULL CHECK(format IN('choice','fill')),knowledge_type TEXT NOT NULL CHECK(knowledge_type IN('noun','verb','adjective','logic','domain')),question_text TEXT NOT NULL,candidates TEXT,correct_answer TEXT,topic_tag TEXT,created_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS answers(id INTEGER PRIMARY KEY,question_id INTEGER NOT NULL REFERENCES questions(id),user_answer TEXT NOT NULL,quality INTEGER NOT NULL CHECK(quality IN(0,1,2)),created_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS scoring_records(id INTEGER PRIMARY KEY,original_text TEXT NOT NULL,total_score INTEGER NOT NULL CHECK(total_score BETWEEN 1 AND 5),accuracy INTEGER NOT NULL CHECK(accuracy BETWEEN 1 AND 5),specificity INTEGER NOT NULL CHECK(specificity BETWEEN 1 AND 5),naturalness INTEGER NOT NULL CHECK(naturalness BETWEEN 1 AND 5),structure INTEGER NOT NULL CHECK(structure BETWEEN 1 AND 5),register INTEGER NOT NULL CHECK(register BETWEEN 1 AND 5),main_issues TEXT NOT NULL,suggestions TEXT NOT NULL,rewrite TEXT NOT NULL,created_at TEXT NOT NULL);`);
const pct=(n:number,d:number)=>d?Math.round(n*1000/d)/10:0;
export function recordAnswer(input:{format:QuestionFormat;question:string;knowledge_type:KnowledgeType;topic_tag?:string;user_answer:string;quality:Quality;candidates?:string[];correct?:string}){return db.transaction(()=>{const now=new Date().toISOString();const q=db.prepare('INSERT INTO questions(format,knowledge_type,question_text,candidates,correct_answer,topic_tag,created_at) VALUES(?,?,?,?,?,?,?)').run(input.format,input.knowledge_type,input.question,input.candidates?JSON.stringify(input.candidates):null,input.correct??null,input.topic_tag??null,now);db.prepare('INSERT INTO answers(question_id,user_answer,quality,created_at) VALUES(?,?,?,?)').run(q.lastInsertRowid,input.user_answer,input.quality,now);return {question_id:q.lastInsertRowid};})();}
export function saveScore(card:ScoreCard){const d=card.dimensions;const r=db.prepare('INSERT INTO scoring_records(original_text,total_score,accuracy,specificity,naturalness,structure,register,main_issues,suggestions,rewrite,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(card.original_text,card.total_score,d.accuracy,d.specificity,d.naturalness,d.structure,d.register,card.main_issues,JSON.stringify(card.suggestions),card.rewrite,new Date().toISOString());return Number(r.lastInsertRowid)}
function mapRows(sql:string){return db.prepare(sql).all() as any[]}
export function getStats(){const empty={total:0,usable:0,good:0,needs_work:0,usable_rate:0,good_rate:0,needs_work_rate:0};const overall=(db.prepare(`SELECT COUNT(*) total,SUM(CASE WHEN quality>=1 THEN 1 ELSE 0 END) usable,SUM(CASE WHEN quality=2 THEN 1 ELSE 0 END) good,SUM(CASE WHEN quality<2 THEN 1 ELSE 0 END) needs_work FROM answers`).get() as any); const total=overall.total??0; const o={...overall,usable:overall.usable??0,good:overall.good??0,needs_work:overall.needs_work??0,usable_rate:pct(overall.usable??0,total),good_rate:pct(overall.good??0,total),needs_work_rate:pct(overall.needs_work??0,total)};
const agg=`COUNT(*) total,SUM(CASE WHEN a.quality>=1 THEN 1 ELSE 0 END) usable,SUM(CASE WHEN a.quality=2 THEN 1 ELSE 0 END) good,SUM(CASE WHEN a.quality<2 THEN 1 ELSE 0 END) needs_work,ROUND(SUM(CASE WHEN a.quality>=1 THEN 1 ELSE 0 END)*100.0/COUNT(*),1) usable_rate,ROUND(SUM(CASE WHEN a.quality=2 THEN 1 ELSE 0 END)*100.0/COUNT(*),1) good_rate,ROUND(SUM(CASE WHEN a.quality<2 THEN 1 ELSE 0 END)*100.0/COUNT(*),1) needs_work_rate`;
return {overall:total?o:empty,weak_types:mapRows(`SELECT q.knowledge_type,${agg} FROM answers a JOIN questions q ON a.question_id=q.id GROUP BY q.knowledge_type ORDER BY good_rate ASC,usable_rate ASC`),format_comparison:mapRows(`SELECT q.format,${agg} FROM answers a JOIN questions q ON a.question_id=q.id GROUP BY q.format`),topic_distribution:mapRows(`SELECT topic_tag,COUNT(*) total FROM questions WHERE topic_tag IS NOT NULL GROUP BY topic_tag ORDER BY total DESC`),writing_summary:db.prepare('SELECT COUNT(*) total_records,ROUND(AVG(total_score),1) average_total_score,ROUND(AVG(accuracy),1) average_accuracy,ROUND(AVG(specificity),1) average_specificity,ROUND(AVG(naturalness),1) average_naturalness,ROUND(AVG(structure),1) average_structure,ROUND(AVG(register),1) average_register FROM scoring_records').get()};}
